#!/bin/bash

# Change working directory to place where this script is saved
cd "$(dirname "$0")"

source externals/bashutils/array
source externals/bashutils/validation
source externals/bashutils/colors
source externals/bashutils/error

source functions.sh

bkp::load_main_config

bkp::backup "${1}"
