#!/bin/bash

# Change working directory to place where this script is saved
cd "$(dirname "$0")"

source externals/bashutils/array
source externals/bashutils/validation
source externals/bashutils/colors
source externals/bashutils/error
source externals/bashutils/macnotify

source functions.sh

bkp::load_main_config
bkp::validate_all_configs

while :
do
  bkp::process
	sleep "${REFRESH_INTERVAL}"
done
