#!/bin/bash

# Change working directory to place where this script is saved
cd "$(dirname "$0")"

source externals/bashutils/array
source externals/bashutils/validation
source externals/bashutils/colors
source externals/bashutils/error
source externals/bashutils/macnotify

source functions.sh

echo "Loading main configuration"

bkp::load_main_config

echo "Waiting ${START_DELAY} seconds to start backup daemon"

sleep "${START_DELAY}"

echo "Loading and validating backups configurations"

bkp::validate_all_configs

echo "Backup daemon started"

while :
do
  bkp::process
  sleep "${REFRESH_INTERVAL}"
done
